15_5_8 Ave Caesar Encoding Program
sergeroshe/Stepik_course pull request #133
Opened 2023-06-15 15:12 UTC by sergeroshe

2023-06-17 08:14 UTC, YanumVlad requested changes

2023-06-17 08:14 UTC, YanumVlad commented on 15_mini_project_work/5_8_ave_caesar.py
> +    source_word_list = source_string.split()
Fix code duplicates

2023-06-17 08:41 UTC, sergeroshe commented on 15_mini_project_work/5_8_ave_caesar.py
> +    source_word_list = source_string.split()
Fixed split method repeating

2023-06-20 12:45 UTC, YanumVlad approved these changes

2023-06-20 12:45 UTC, merged