15_7_12 Simplify user input processing
sergeroshe/Stepik_course pull request #182
Opened 2023-06-30 13:00 UTC by sergeroshe

2023-07-03 09:33 UTC, YanumVlad requested changes

2023-07-03 09:33 UTC, YanumVlad commented on 15_mini_project_work/7_hangman_game.py
> +    #  print_game_result extract function
print_game_result extract function

2023-07-03 09:37 UTC, YanumVlad requested changes

2023-07-03 09:37 UTC, YanumVlad commented on 15_mini_project_work/7_hangman_game.py
> +        game_won = input_string == hidden_word or word_completion_list == word_char_list
Remove doubled calc

2023-07-04 11:22 UTC, YanumVlad requested changes

2023-07-04 11:22 UTC, YanumVlad commented on 15_mini_project_work/7_hangman_game.py
>      word_completion = FILLING_CHAR * len(guessed_word)
Extract to separate function

2023-07-04 11:23 UTC, YanumVlad requested changes

2023-07-04 11:23 UTC, YanumVlad commented on 15_mini_project_work/7_hangman_game.py
>      tries_remained = MAX_TRIES_COUNT
Remove unused var

2023-07-04 16:24 UTC, sergeroshe commented on 15_mini_project_work/7_hangman_game.py
>      tries_remained = MAX_TRIES_COUNT
Done

2023-07-05 12:54 UTC, YanumVlad requested changes

2023-07-05 12:54 UTC, YanumVlad commented on 15_mini_project_work/7_hangman_game.py
> +    game_run(MAX_TRIES_COUNT, guessed_word)
remove double meaning: hidden_word / guessed_word

2023-07-05 13:04 UTC, YanumVlad requested changes

2023-07-05 13:04 UTC, YanumVlad commented on 15_mini_project_work/7_hangman_game.py
> +    enter_guess_prompt = f'{ENTER_GUESS_PROMPT_P_1}{hidden_word_len}{ENTER_GUESS_PROMPT_P_2}{COLON_SEP}\n'
Replace with format call

2023-07-05 13:54 UTC, sergeroshe commented on 15_mini_project_work/7_hangman_game.py
> +    game_run(MAX_TRIES_COUNT, guessed_word)
Removed

2023-07-05 14:16 UTC, YanumVlad approved these changes

2023-07-05 14:16 UTC, merged